### ISSUE TITLE
Server Public IP not available with port

### ISSUE THREAD

**Issue by trustflut** [etechd/L3MON#11]
Hi everyone I have setup L3MON Successfully on my Ubuntu 18.04 LTS Google Cloud Compute Engine  but when I fire `sudo pm2 start index.js` it worked successfully but when I go to my Compute Engine Control panel and copy External IP address to open the L3MON control panel with `http://<EXTERNAL IP>:22533` url it doesn't open.

**Comment by Jack-Rogers** [comment]
You may have to open ports `22433` & `22222`, please see [This Page](https://stackoverflow.com/questions/21065922/how-to-open-a-specific-port-such-as-9090-in-google-compute-engine) for how to do that :)

**Comment by Jack-Rogers** [comment]
Closing as stale / non-issue
