### ISSUE TITLE
Java Not Installed

### ISSUE THREAD

**Issue by Aldaet** [etechd/L3MON#14]
Localhost log when build apk 

` 02/12/2019, 09:35:40 => ERROR | Build Failed - Java Not Installed
02/12/2019, 09:29:37 => ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/root/L3MON/server/app/factory/sign.jar" "/root/L3MON/server/assets/webpublic/build.apk" Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more `

java -version 
`Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
`

javac -vesrion
`Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
javac 1.8.0_212`

and java  installed error

**Comment by Jack-Rogers** [comment]
Did you follow the guide to installing Java?

Yous should expect too see an output like this 
```shell
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
```
when you run `java -version`

Please uninstall Java and Try again

**Comment by Jack-Rogers** [comment]
Closing as stale / non-issue

**Comment by Aldaet** [comment]
Localhost log when build apk

02/12/2019, 09:35:40 => ERROR | Build Failed - Java Not Installed 02/12/2019, 09:29:37 => ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/root/L3MON/server/app/factory/sign.jar" "/root/L3MON/server/assets/webpublic/build.apk" Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more

java -version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true openjdk version "1.8.0_212" OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01) OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)

javac -vesrion
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true javac 1.8.0_212

and java installed error

**Comment by Jack-Rogers** [comment]
This issue will be continued at #19

**Comment by fana-svg** [comment]
Localhost not connecting ....
Is there any solutions
