### ISSUE TITLE
Builder not work

### ISSUE THREAD

**Issue by zunzail** [etechd/L3MON#15]
i have this error
Sign Command Failed - Command failed: java -jar "/home/axel/Desktop/LEMON/app/factory/sign.jar" "/home/axel/Desktop/LEMON/assets/webpublic/build.apk" Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more

java -version

openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment (build 11.0.4+11-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.4+11-post-Debian-1, mixed mode, sharing)

**Comment by ikevinsolomon** [comment]
Use Java 8 please.

**Comment by Jack-Rogers** [comment]
As @ikevinsolomon noted, Please follow the guide for installation and use Java 8,
