### ISSUE TITLE
ERROR |  Build Failed - File Patch Error - WRITE (Help ☹️) 

### ISSUE THREAD

**Issue by Skladak04** [etechd/L3MON#18]
I apologize for my bad English, but I have a problem, the whole process of building the application hangs on finalization and the error code looks like 07/01/2020, 02:22:14 => ERROR |  Build Failed - File Patch Error - WRITE

**Comment by Skladak04** [comment]
#Closed

**Comment by Jack-Rogers** [comment]
Glad you sorted the issue! 
What did you do to fix this? (might be helpful for someone else in the future!)

**Comment by sudo-WearTherinG** [comment]
U might think it stuck on finalizing screen but thats not the issue,
after u try to build the apk but it's stuck u may think its not working.  go back to folder
lemon/L3MON-v1.0.0/assets/webpublic
there will be 2 apk files ( build.apk and build.s.apk ) the file u want here is named " build.apk "
send it to your android and  install it, but it will not install becouse its not signed so u have to create jar signer keystore file to sign it yourself, search on google or someting, then sign the apk yourself and wollha. u can install it and open it. login to lemon website and manage your android.

**Comment by johnnyyii** [comment]
Android vm hitting error install apk "there was a problem parsing the package". I've deleted the apk file in L3MON-v1.0.0/assets/webpublic/build.s.apk but somehow when I run the apk_builder again. It doesn't generate the apk file. In the Event log "build failed - file patch error - write". Can advise? Many thanks :)
