### ISSUE TITLE
embed in other apk

### ISSUE THREAD

**Issue by pretech86** [etechd/L3MON#21]
treally thanks for the tool , i appreciate you really 
but can you add the following feature
1- embed the payload in original apk 
2- bypass google play protection to prevent the victime to activate unknown resources
3- reaching to facebook and whatsup messages 

also if i want to use it with ngrok i should put the ngrok ip and port only or what i should do ?

**Comment by siceinformatica** [comment]
Hi for ngrok I did:
run ngrok
run lemon 

$./ngrok tcp 22222 --remote-addr=<YOUR NGROK ADDRESS>:23508

to build apk I used:
HTTP:<YOUR NGROK ADDRESS>
PORT: 23508 instead default one 22222

**Comment by pretech86** [comment]
thanks it working now

**Comment by Jack-Rogers** [comment]
Sorry, This app is made for Administration and Educational purposes, Bypassing Google play and packaging with another application says to me you want to be using it maliciously, so in short. no.

Thanks, @siceinformatica for helping with ngrok!
