### ISSUE TITLE
Stuck on "Finalizing" & "build.s.apk" is an empty file. 

### ISSUE THREAD

**Issue by falconistic** [etechd/L3MON#24]
![Screenshot from 2020-01-14 23-33-06](https://user-images.githubusercontent.com/48550682/72391842-50141600-3726-11ea-81ea-432d867aee20.png)
![Screenshot from 2020-01-14 23-27-10](https://user-images.githubusercontent.com/48550682/72391609-8309da00-3725-11ea-876d-d2c29501732e.png)
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Debian-2)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Debian-2, mixed mode, sharing)

The program does generate the build.apk and  build.s.apk, but the file size for a build.s.apk is 0.
-------------------------------------------------------------------------------------------------------------------------

**Comment by Jack-Rogers** [comment]
Please use JDK 8 not 11
