### ISSUE TITLE
npm install

### ISSUE THREAD

**Issue by sanjeetkumarpatel** [etechd/L3MON#27]
root@kali:~/Desktop/L3MON# npm install
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-20T18_09_16_141Z-debug.log
root@kali:~/Desktop/L3MON# ls
app  assets  clientData  includes  index.js  node_modules  package.json  package-lock.json
root@kali:~/Desktop/L3MON# pm2 start index.js
[PM2] Starting /root/Desktop/L3MON/index.js in fork_mode (1 instance)
[PM2] Done.

root@kali:~/Desktop/L3MON# ls
app  assets  clientData  includes  index.js  node_modules  package.json  package-lock.json

**Comment by Jack-Rogers** [comment]
> npm ERR! This is an error with npm itself. Please report this error at:
> npm ERR! https://npm.community

Looks like you might have an issue with your NPM installation, please try reinstalling it.
