### ISSUE TITLE
ngrok alternative 

### ISSUE THREAD

**Issue by outusuke** [etechd/L3MON#3]
Any tools similar to ngrok free to run this program?
i tried localxpose.io but the free version only allows http

**Comment by Jack-Rogers** [comment]
The Software runs on 2 ports, one for administration and one for external device access.
you'll need to forward port `22222`, unless you've changed it in `server/includes/const.js:6`.

As we use Socket.io, it should run over a plain HTTP connection, you could try changing the port to `80` and using localxpose.io with that? you'll have to also rebuild the APK!

I hope this helps!

**Comment by Jack-Rogers** [comment]
HTTP runs on the TCP network model?

**Comment by outusuke** [comment]
I meant it only works using tcp ngrok

**Comment by Jack-Rogers** [comment]
try changing the port found here: `server/includes/const.js:6` to port 80 and using localxpose.io
This software was built to be run on a VPS ideally, you can get a cheap one from OVH

**Comment by outusuke** [comment]
yes vps and better but i wanted to try some free alternative before

**Comment by pretech86** [comment]
@outusuke can you tell me what you did to use it wuth ngrok 
i use this 
tcp://0.tcp.ngrok.io:18368

what after that ? sorry to interrupt you

**Comment by Lorenz11x** [comment]
@pretech86 is ngrok tcp 22222 and it works perfectly !! 
Thanks  Jack-Rogers !!! ;)

**Comment by yashgaikwad002** [comment]
I have issue of not building the apk when i specify the manual port number in build tab and const.js. Any way to get around it?
