### ISSUE TITLE
Devices Showing offline 

### ISSUE THREAD

**Issue by maheshphule22** [etechd/L3MON#4]
I am able to see devices after installing apk on android. But they are offline all the time. 
Please Help

**Comment by Jack-Rogers** [comment]
The application may be being killed by some battery monitoring task, it should respawn on a notification or on a clipboard event. 

Alternatively, could it be possible that your IP has changed?

**Comment by maheshphule22** [comment]
I have given all permissions from settings and disabled battery
optimization for this application, autorun enabled etc.
To followup this case
1. How can I check if application is running or not?
2. How can I start the application? I don't have any way from which I can
launch the application.

IP change is not the case, I checked it. Admin panel is up and running. And
I can access it on that IP only. The same IP is configured while building
the apk.

Thanks and regards,

**Comment by Jack-Rogers** [comment]
Try going to your dialer and dialing `*#*#8088#*#*` This should bring up one of the original menus, though more importantly, start the service running again.

If this doesn't bring up a menu, try recompiling and re installing the APK.

To see if the app is running, goto `Android Settings -> Apps & Notifications -> See All *** Apps` and look for `Process Manager`, click it and you should see 2 buttons `Uninstall` and `Force Stop`, if `Force Stop` is grayed out, the app is not running.

If all of the above still doesn't solve your issue, can you download ADB tools and connect to the phones shell and run this command: `logcat | grep L3MON` and pop the output on Gist/Pastebin for me; please?

Thanks

**Comment by maheshphule22** [comment]
Yes, Force stop option is disabled.

And adb logs shows this

 W/BroadcastQueueInjector: Unable to launch app com.etechd.l3mon/10172 for
broadcast Intent { act=android.provider.Telephony.SECRET_CODE
dat=android_secret_code://8088 flg=0x10000010 }: process is not permitted
to  auto start

I have enabled all permissions from settings. Disabled all battery
optimizations.

Thanks

**Comment by Jack-Rogers** [comment]
What device is this running on, Is it a Xaiomi? If so, please have a read thru this https://stackoverflow.com/questions/29627856/reboot-receiver-is-not-working-in-xiaomi-phones

It appears the app is being blocked from starting by some process manager on your device still. 

Thanks

**Comment by maheshphule22** [comment]
Yes it is a Xaiomi device, I will follow those answers and try to make
changes, and will keep you updated.
Thanks And Regards

**Comment by maheshphule22** [comment]
It started working.

So on Xaiomi devices, one need to disable MIUI Optimization setting from developer options.

(And of course grant permissions and allow auto start and disable battery optimization - which I already did before starting this thread.:P)

Thanks @Jack-Rogers for the help. 
L3MON Tested and working as advertised. :)

**Comment by Jack-Rogers** [comment]
Excellent stuff, Glad you got it going!
