### ISSUE TITLE
dependencies install fail no repository field

### ISSUE THREAD

**Issue by soyabkhanmalek** [etechd/L3MON#5]
when trying to install dependencies with npm install shows :-
npm WARN L3MON@1.0.0 No repository field.

audited 280 packages in 4.695s
found 0 vulnerabilities

**Comment by Jack-Rogers** [comment]
Is this when cloning or when downloading the release ZIP?

**Comment by soyabkhanmalek** [comment]
🤐

**Comment by dilwarSingh** [comment]
I am also stuck with the same problem. I downloaded the release ZIP.
Any suggestions

**Comment by amir1376irani** [comment]
@soyabkhanmalek  @dilwarSingh  you must enter command '''npm install''' in server directory not in root place of project.

@Jack-Rogers  unfortunately it's not stated in documentation (README.md)
