### ISSUE TITLE
L3MON Manager

### ISSUE THREAD

**Issue by ch4iril** [etechd/L3MON#6]
i try login to L3mon Manager but always bad login
on maindb.json i have change username and password , i know that for login manager next

but always bad login again again and again

somebody can help me.........please

**Comment by ch4iril** [comment]
fix to login no problemo

why apk not work...........
can you tell me how config ip using ngrok, may i should change port 22222 ?
i use ngrok tcp

thanks

**Comment by ch4iril** [comment]
fix all working

closed, thanks

**Comment by alfonce180** [comment]
the compiled app is not working actually its 0 bytes please help
thank you....

**Comment by yashgaikwad002** [comment]
Hey im still facing the same issue
