### ISSUE TITLE
[Code Fix] Location block needs a little refactor to the following 

### ISSUE THREAD

**Issue by ikevinsolomon** [etechd/L3MON#8]
https://github.com/etechd/L3MON/blob/acbc29be4db0bd2cf297dcbf61086fa6829c9e37/server/includes/clientManager.js#L256
socket.on(CONST.messageKeys.location, (data) => {
	
		if (Object.keys(data).length !== 0 && data.hasOwnProperty("latitude") && data.hasOwnProperty("longitude") ) {
			client.get('GPSData').push({
				time: new Date(),
				enabled: data.enabled || false,
				latitude: data.latitude || 0,
				longitude: data.longitude || 0,
				altitude: data.altitude || 0,
				accuracy: data.accuracy || 0,
				speed: data.speed || 0
			}).write();
			logManager.log(CONST.logTypes.success, clientID + " GPS Updated");

		} else {
			logManager.log(CONST.logTypes.error, clientID + " GPS Recieved No Data");
			logManager.log(CONST.logTypes.error, clientID + " GPS LOCATION SOCKET DATA" + JSON.stringify(data) );
		}`

});

**Comment by Jack-Rogers** [comment]
Added to the `v1.1.0` release, Thanks!
